### ISSUE TITLE
error in vcf file

### ISSUE THREAD

**Issue by ElenaSLuis** [drneavin/Demultiplexing_Doublet_Detecting_Docs#11]
Hey,
I'm trying to run Demuxafy.sif popscle ,

Firstly I try to do without filter as say in the tutorial of Demuxafy : https://demultiplexing-doublet-detecting-docs.readthedocs.io/en/latest/DataPrep.html with the data: [GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding.vcf](https://www.dropbox.com/s/1akkxa7s9u485ka/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding.vcf)
 also I tried with GeneFiltered.

Firstly I do:
apptainer exec --bind /home/elenasl/scRNAseq:/home/elenasl/ Demuxafy.sif popscle \
dsc-pileup --sam /home/elenasl/scRNAseq/cellranger/run_msc_polyIC_Ranger_count/outs/possorted_genome_bam.bam \
--tag-group /home/elenasl/scRNAseq/cellranger/run_msc_polyIC_Ranger_count/outs/filtered_feature_bc_matrix/barcodes.tsv.gz \
--vcf /home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding.vcf \
--out /home/elenasl/scRNAseq/freemuxlet/pileup_polyIC \

also I try to sort vcf and filter bam as say in recommendations of Popscle:
#sort
/home/elenasl/scRNAseq/freemuxlet/sort_vcf_same_as_bam.sh \
/home/elenasl/scRNAseq/cellranger/run_msc_polyIC_Ranger_count/outs/possorted_genome_bam.bam \
/home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding.vcf \
>/home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding_Sorted.vcf

#filter bam
/home/elenasl/scRNAseq/freemuxlet/filter_bam_file_for_popscle_dsc_pileup.sh \
/home/elenasl/scRNAseq/cellranger/run_msc_polyIC_Ranger_count/outs/possorted_genome_bam.bam \
/home/elenasl/scRNAseq/cellranger/run_msc_polyIC_Ranger_count/outs/filtered_feature_bc_matrix/barcodes.tsv.gz \
/home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding_Sorted.vcf \
/home/elenasl/scRNAseq/freemuxlet/data/samples_to_demultiplex.filter_bam_file_for_popscle_dsc_pileup.bam > outbam

#run popscle:
apptainer exec --bind /home/elenasl/scRNAseq:/home/elenasl/ Demuxafy.sif popscle \
dsc-pileup --sam /home/elenasl/scRNAseq/freemuxlet/data/samples_to_demultiplex.filter_bam_file_for_popscle_dsc_pileup.bam \
--tag-group /home/elenasl/scRNAseq/cellranger/run_msc_polyIC_Ranger_count/outs/filtered_feature_bc_matrix/barcodes.tsv.gz \
--vcf /home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding_Sorted.vcf \
--out /home/elenasl/scRNAseq/freemuxlet/pileup_polyIC \

the error is all the time the same:
Initializing BCF reader..
[E::hts_open_format] Failed to open file "/home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding_Sorted.vcf" : No such file or directory
NOTICE [2022/12/30 11:56:24] - Skipping to read non-existent file /home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding_Sorted.vcf

FATAL ERROR -
[/opt/popscle/bcf_chunked_reader.cpp:66 void BCFChunkedReader::init(genomeLoci*)] Cannot open any of the input file. Last file name is /home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding_Sorted.vcf

terminate called after throwing an instance of 'pException'
  what():  Exception was thrown
Aborted (core dumped)

any idea?

**Comment by drneavin** [comment]
Hi @ElenaSLuis, I apologize for my tardy response - I have been on holiday and do not look at messages during that time. 

I don't think this is causing the issue but you are binding two directories - one of which is the parent of the other so that is unnecessary. Instead, you could do:

```
apptainer exec --bind /home/elenasl/ Demuxafy.sif
```

To help identify the issue, could you do a few things:

1. Can you do 
```
ls /home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding_Sorted.vcf
```

2. If it exists, can you run

```
apptainer exec --bind /home/elenasl/ Demuxafy.sif ls /home/elenasl/scRNAseq/freemuxlet/vcf_chr/GRCh38_1000G_MAF0.01_ExonFiltered_ChrEncoding_Sorted.vcf
```

If that works, it may have something to do with `apptainer`. I haven't tried running this image through apptainer before. If it works, that's great! Do you have `singularity` on your system or on a system you can test?

Let me know how those commands go and we can troubleshoot from there.

**Comment by ElenaSLuis** [comment]
Hey! finally it works it was just remove bind after do it for first time:

apptainer exec Demuxafy.sif ls

**Comment by drneavin** [comment]
Great, glad you were able to get it to work and glad to know that it works with `apptainer`!
