### ISSUE TITLE
Issue with souporcell vartrix step

### ISSUE THREAD

**Issue by changostraw** [drneavin/Demultiplexing_Doublet_Detecting_Docs#12]
Hi - Thanks so much for this pipeline! 
I am getting the same issue as you were getting with vartrix that you posted about here: https://github.com/wheaton5/souporcell/issues/126. I am using the code:
`singularity exec Demuxafy.sif souporcell_pipeline.py -i $BAM -b $BARCODES -f $FASTA -t $THREADS -o $SOUPORCELL_OUTDIR -k $N --common_variants $VCF`
with a vcf from the 1000Genomes and vartrix fails the same way you described. 

I didn't get this issue using:
`singularity exec Demuxafy.sif souporcell_pipeline.py -i $BAM -b $BARCODES -f $FASTA -t $THREADS -o $SOUPORCELL_OUTDIR -k $N --known_genotypes $VCF --known_genotypes_sample_names donor1 donor donor3 donor4` with a vcf of genotype data from my cohort. 

In the thread above you mentioned on Oct 31, 2022 that this was fixed by using the most updated vartrix. If I downloaded Demuxafy.sif before Oct 2022 would that mean I am using an old version of vartrix as well? Should I download a new image?  Apologies if this is a basic question. I am learning bioinformatics. Thanks!

**Comment by drneavin** [comment]
Hi @changostraw!

Glad you've been using Demuxafy! And thanks for providing feedback.

I think it makes sense that you would only see the issue when using common variants because souporcell uses freebayes to call SNP genotypes when known genotypes are provided and doesn't use vartrix as an intermediary.

But it looks like I haven't generated a new Demuxafy image with the newest version of vartrix (looks like Demuxafy v2.0.0 used vartrix 1.1.3 but should be at least 1.1.22). I'll update it today and let you know when it has been uploaded online. It may take a couple of days depending on if I have any issues with new package installation requirements.

**Comment by changostraw** [comment]
thanks so much @drneavin!

**Comment by drneavin** [comment]
Completed! The newest singularity image ([v2.0.1](https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/releases/tag/v2.0.1)) contains vartrix v1.1.22.

Thanks so much for pointing out this issue so I could resolve it!

**Comment by changostraw** [comment]
Hi @drneavin I updated the file and am running souporcell again and will let you know. However, now when I try to run the combine script for example:
`singularity exec --bind /project/rrg-gturecki/Sarah/Multiplexing_Test/Demuxafy /project/rrg-gturecki/Sarah/Demuxafy.sif Combine_Results.R \
  -o /project/rrg-gturecki/Sarah/Multiplexing_Test/Demuxafy/cecum_poolA_noGT_combined_results.tsv \
  --freemuxlet /project/rrg-gturecki/Sarah/Multiplexing_Test/Demuxafy/Freemuxlet/cecum_poolA \
  --souporcell /project/rrg-gturecki/Sarah/Multiplexing_Test/Demuxafy/Souporcell_noGT/cecum_poolA \  
  --vireo /project/rrg-gturecki/Sarah/Multiplexing_Test/Demuxafy/Vireo/cecum_poolA_noGT \
  --scds /project/rrg-gturecki/Sarah/Multiplexing_Test/Demuxafy/Scds/cecum_poolA \
  --method "MajoritySinglet"`

I get an error:
/opt/Demultiplexing_Doublet_Detecting_Docs/scripts/Combine_Results.R: error: unrecognized arguments:
--vireo not found! Similar commands: "envideo"

Was something changed in the latest update to not include vireo as an option?

**Comment by changostraw** [comment]
sorry - scratch that - there was a small syntax issue - thanks again!

**Comment by drneavin** [comment]
Great! Glad you were able to resolve the issue!
