### ISSUE TITLE
wget https://www.dropbox.com/s/vpezjhxj9ek609x/Demuxafy.sif

### ISSUE THREAD

**Issue by Tan-GuangHui** [drneavin/Demultiplexing_Doublet_Detecting_Docs#16]
--2023-02-17 11:21:35--  https://www.dropbox.com/s/vpezjhxj9ek609x/Demuxafy.sif
Resolving www.dropbox.com (www.dropbox.com)... 31.13.85.34, 2001::453f:ba1f
Connecting to www.dropbox.com (www.dropbox.com)|31.13.85.34|:443... 

failed: Connection timed out.
Connecting to www.dropbox.com (www.dropbox.com)|2001::453f:ba1f|:443... failed: Network is unreachable.

**Comment by drneavin** [comment]
Hi @Tan-GuangHui ,

This is strange because I have no issues downloading it using that wget command (`wget https://www.dropbox.com/s/vpezjhxj9ek609x/Demuxafy.sif`).

Does the same happen for the md5 file (`wget https://www.dropbox.com/s/m275g7scncinn0e/Demuxafy.sif.md5`)? If not, I think it may be a size issue and there may be limitations to the wget size you can download on your system.

Let me know what else you've tried to resolve this.

Cheers,
Drew

**Comment by Tan-GuangHui** [comment]
Thank you very much, but now there are new problems.

singularity exec Demuxafy.sif souporcell_pipeline.py \
 -i /home/tanguanghui/zy-cattle/FP200000433BL_A2_web_3.Aligned.sortedByCoord.out.merge.q10.dedup.target.bam\
 -b /root/cpdb/BeadLocationsForR.csv \
 -f /root/cpdb/ARS-UCD1.2_Btau5.0.1Y.fa \
 -t 4 \
 -o /root/cpdb \
 -k 2 \
 --known_genotypes /root/cpdb/Fetal_E100041723_L01_CATsquvR191697-608_1.gvcf.gz \
 --known_genotypes_sample_names Fetal maternal



Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 79, in <module>
    reader = vcf.Reader(open(args.known_genotypes))
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/vcf/parser.py", line 300, in __init__
    self._parse_metainfo()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/vcf/parser.py", line 317, in _parse_metainfo
    line = next(self.reader)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/vcf/parser.py", line 280, in <genexpr>
    self.reader = (line.strip() for line in self._reader if line.strip())
  File "/opt/conda/envs/py36/lib/python3.6/codecs.py", line 644, in __next__
    line = self.readline()
  File "/opt/conda/envs/py36/lib/python3.6/codecs.py", line 557, in readline
    data = self.read(readsize, firstline=True)
  File "/opt/conda/envs/py36/lib/python3.6/codecs.py", line 497, in read
    newdata = self.stream.read(size)
  File "/opt/conda/envs/py36/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/opt/conda/envs/py36/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/opt/conda/envs/py36/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/opt/conda/envs/py36/lib/python3.6/gzip.py", line 406, in _read_gzip_header
    magic = self._fp.read(2)
  File "/opt/conda/envs/py36/lib/python3.6/gzip.py", line 91, in read
    self.file.read(size-self._length+read)
  File "/opt/conda/envs/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)

**Comment by drneavin** [comment]
Hi @Tan-GuangHui ,

I think this is related to the vcf file you are providing which is gzipped. Souporcell hasn't implemented the ability to deal with gzipped files and the error seems to be indicating that is where it is getting caught up (in reading the vcf.gz). Can you try unzipping the vcf file and rerunning and let me know if that resolves your issue?

Cheers,
Dres

**Comment by Tan-GuangHui** [comment]
Hello, teacher, I have a new problem.
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 80, in <module>
    assert len(reader.samples) >= int(args.clusters), "number of samples in known genotype vcfs is less than k/clusters"
AssertionError: number of samples in known genotype vcfs is less than k/clusters

**Comment by drneavin** [comment]
Hi @Tan-GuangHui ,

I think there might not be two individuals in your vcf. Can you provide the output of `gunzip -c /root/cpdb/Fetal_E100041723_L01_CATsquvR191697-608_1.gvcf.gz | grep "#CHROM"`? Or, alternatively, if you have already gunzipped the vcf, `grep "#CHROM /root/cpdb/Fetal_E100041723_L01_CATsquvR191697-608_1.gvcf`

**Comment by Tan-GuangHui** [comment]
Now, I have a vcf file containing fetal and maternal mutations. When we run this script, there is no error report, but there is no result output, even if I run it for 12 hours. 

singularity exec Demuxafy.sif souporcell_pipeline.py \
 -i sorted.bam\
 -b BeadLocationsForR.csv \
 -f ARS-UCD1.2_Btau5.0.1Y.fa \
 -t 20\
 -o /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/out \
 -k 2 \
 --known_genotypes /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/chrAll_QC_filter.vcf \
 --known_genotypes_sample_names maternal fetal --ignore true

**Comment by drneavin** [comment]
That is a bit strange. Have you pasted that command exactly as you're entering it? You should have `\` for escapes at the end of each line or have everything on one line like this:
```
singularity exec Demuxafy.sif souporcell_pipeline.py \
-i sorted.bam \
-b BeadLocationsForR.csv \
-f ARS-UCD1.2_Btau5.0.1Y.fa \
-t 20 \
-o /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/out \
-k 2 \
--known_genotypes /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/chrAll_QC_filter.vcf \
--known_genotypes_sample_names maternal fetal --ignore true
```

or 
```
singularity exec Demuxafy.sif souporcell_pipeline.py -i sorted.bam -b BeadLocationsForR.csv -f ARS-UCD1.2_Btau5.0.1Y.fa -t 20 -o /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/out -k 2 --known_genotypes /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/chrAll_QC_filter.vcf --known_genotypes_sample_names maternal fetal --ignore true
```

You should expect to see some files start to populate the output directory immediately when you start running it, although it won't be the final files.

Souporcell can take longer than 12 hours to run but will depend on the number of mapped reads and the number of SNPs in your vcf.

Let me know if you're still having trouble with the command.

Best,
Drew

**Comment by Tan-GuangHui** [comment]
Here's my script






| |
谭光辉（GuangHui-Tan）
|
|
西北农林科技大学动物科技学院，Northwest A&F University
17585473094
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/2/2023 10:36 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [drneavin/Demultiplexing_Doublet_Detecting_Docs] wget https://www.dropbox.com/s/vpezjhxj9ek609x/Demuxafy.sif (Issue #16) |

That is a bit strange. Have you pasted that command exactly as you're entering it? You should have \ for escapes at the end of each line or have everything on one line like this:

singularity exec Demuxafy.sif souporcell_pipeline.py \
-i sorted.bam \
-b BeadLocationsForR.csv \
-f ARS-UCD1.2_Btau5.0.1Y.fa \
-t 20 \
-o /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/out \
-k 2 \
--known_genotypes /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/chrAll_QC_filter.vcf \
--known_genotypes_sample_names maternal fetal --ignore true


or

singularity exec Demuxafy.sif souporcell_pipeline.py -i sorted.bam -b BeadLocationsForR.csv -f ARS-UCD1.2_Btau5.0.1Y.fa -t 20 -o /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/out -k 2 --known_genotypes /work/home/luo_funong/Tan_Guang-hui/mutai_qufen/chrAll_QC_filter.vcf --known_genotypes_sample_names maternal fetal --ignore true


You should expect to see some files start to populate the output directory immediately when you start running it, although it won't be the final files.

Souporcell can take longer than 12 hours to run but will depend on the number of mapped reads and the number of SNPs in your vcf.

Let me know if you're still having trouble with the command.

Best,
Drew

**Comment by drneavin** [comment]
Hi @Tan-GuangHui ,
Unfortunately, the script didn't come through. You can directly email it to me at d.neavin @ garvan.org.au (remove the spaces).

**Comment by drneavin** [comment]
Hi @Tan-GuangHui , I'm closing this since I assume you worked out the issue. Please reopen if that is untrue.

**Comment by guanghui-tan** [comment]
> Hi @Tan-GuangHui , I'm closing this since I assume you worked out the issue. Please reopen if that is untrue.

**Comment by XFWuCN** [comment]
Hi @drneavin and @Tan-GuangHui ,
I faced the same issue about error in wget,I had try 
```
wget -O Demuxafy.sif 'https://www.dropbox.com/scl/fi/g0cuyjwomdavom6u6kb2v/Demuxafy.sif?rlkey=xfey1agg371jo4lubsljfavkh&' 
```
and 
```
wget https://www.dropbox.com/s/vpezjhxj9ek609x/Demuxafy.sif
```
 and code from https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/issues/34#issuecomment-1899171720. But still both Demuxafy.sif and Demuxafy.sif.md5 could not be download.I also tried to download files to my PC,but it's too big.Do  you have any idea?
