### ISSUE TITLE
Assign_Indiv_by_Geno.R Pearson Correlation Issue

### ISSUE THREAD

**Issue by SimonDMurray** [drneavin/Demultiplexing_Doublet_Detecting_Docs#19]
Hi,

I am trying to run `Assign_Indiv_by_Geno.R` on some souporcell output that used the `known_genotypes` option. 
When using this script I get the error:
```
Error in cor(as.numeric(pull(ref_df, col)), as.numeric(pull(clust_df,  :
  no complete element pairs
```

However, when googling this issue I found the suggestion to change a line in the `pearson_correlation` function to 
```
df[row,col] <- cor(as.numeric(pull(ref_df, col)), as.numeric(pull(clust_df, row)), method = "pearson", use = "p")
```
which then worked for my sample. 

I wanted to know if this may be an issue with my sample or the script?

If you need any more information please do not hesitate to ask!

Thanks,
Simon

**Comment by SimonDMurray** [comment]
Hi,

I identified the issue. The NA fields were not dropping from my VCF correctly causing the correlation function to fail.

Simon

**Comment by apaikari** [comment]
Hi drneavin,
I have the same problem. 
Error in cor(as.numeric(pull(ref_df, col)), as.numeric(pull(clust_df,  :
  no complete element pairs
Calls: pearson_correlation -> cor
Execution halted.
Do you have any suggestions?

**Comment by drneavin** [comment]
Hi @apaikari, I'm guessing there are no SNPs in common between the two files. I'll add some more messaging about the number of SNPs from each file and the number overlapping in the next release. In the meantime, can you confirm a few things:

1. That there are SNPs in both files. To do this you can use `grep -v "#" <vcf_file> | wc -l` or if it is a vcs.gz file `gunzip -c <gzipped_vcf_file> | grep -v "#" | wc -l`. If this returns 0 for the wc, you know that you have no SNPs which would cause problems with the donor matching and would require some upstream investigation
2. That both files are on the same genome (hg19/GRCh37 or hg38/GRCh38)?
3. That both files use the same nomenclature for the chromosomes (_i.e._ chr1 vs 1)

If the answer to all of these is yes, would you be willing to send me an example of your files or the first 500 rows of them? If you don't want to post online you can email them to me at d.neavin @ garvan.org.au

**Comment by apaikari** [comment]
Hi drneavin, 
Happy 2024! Sorry for the delay in response. I wanted to let you know that I found and solved the problem with the chromosome nomenclature in one of the files. Thank you for your help.

**Comment by drneavin** [comment]
Great, glad this was resolved!
