### ISSUE TITLE
NameError: name 'scanpy' is not defined in scrublet.py

### ISSUE THREAD

**Issue by richardsalisbury** [drneavin/Demultiplexing_Doublet_Detecting_Docs#20]
Hi Dr Neavin,

Thanks for making this excellent tool.
I've had an error trying to run scrublet using the filtered_feature_bc_matrix.h5

NameError: name 'scanpy' is not defined

I am a novice with python but I think it may be that scanpy is not imported up top (apologies if this was in fact my error).

Thanks,

Richard

**Comment by drneavin** [comment]
Hi @richardsalisbury ,

Thanks for your message and bringing this to my attention! I don't often use the h5 file directly so this is an oversight from my end. I'll update the script and singularity image and get back to you when they're completed.

-Drew

**Comment by drneavin** [comment]
Hi @richardsalisbury ,

It should be sorted in [v2.0.2](https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/releases/tag/v2.0.2). Please reopen and let me know if it is still an issue.

Cheers,
Drew
