### ISSUE TITLE
Tutorial: FASTA file missing for `souporcell`

### ISSUE THREAD

**Issue by mschilli87** [drneavin/Demultiplexing_Doublet_Detecting_Docs#22]
`souporcell` requires the `-f` flag and while the turorial mentiones `FASTA` a required parameter, no such file is provided with the (reduced) test dataset. Mentioning which genome assembly these data where mapped to to generate the provided `BAM` would be very useful, ideally even accompanied by a direct download link.

**Comment by drneavin** [comment]
Thanks for the suggestions @mschilli87!

The data are aligned to hg38. I'm making updates to the documents now so I'll be sure to clarify this in the documentation.

**Comment by mschilli87** [comment]
@drneavin: Thanks for the fast response. I'll leave this open as a reminder until the documentation is updated.

**Comment by drneavin** [comment]
Added information on the genome and fasta download location to the [Data Prep page](https://demultiplexing-doublet-detecting-docs.readthedocs.io/en/latest/DataPrep.html#test-dataset)
