### ISSUE TITLE
Singularity image: Add BioPython >= 1.73 to `py36` env for compressed FASTA support for souporcell

### ISSUE THREAD

**Issue by mschilli87** [drneavin/Demultiplexing_Doublet_Detecting_Docs#23]
Providing a `.fa.gz` file to `souporcell`'s `-f` flag results in the following error:

```
checking modules
imports done
checking bam for expected tag
checking fasta
Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/pyfaidx/__init__.py", line 396, in __init__
    from Bio import bgzf
ModuleNotFoundError: No module named 'Bio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 111, in <module>
    fasta = pyfaidx.Fasta(args.fasta, key_function = lambda key: key.split()[0])
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/pyfaidx/__init__.py", line 1081, in __init__
    build_index=build_index)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/pyfaidx/__init__.py", line 403, in __init__
    "BioPython >= 1.73 must be installed to read block gzip files.")
ImportError: BioPython >= 1.73 must be installed to read block gzip files.
```

I understand this as `souporcell` supporting compressed FASTA input, but conditioned on an optional dependence on BioPython >= 1.73. So adding this to `Demuxay.sif`'s `/opt/conda/envs/py36/lib/python3.6/site-packages` would safe Demuxafy users from storing a decompressed copy of their genome FASTA file while runnning `souporcell`.

**Comment by drneavin** [comment]
Thanks for the recommendation @mschilli87! Unfortunately, this update won't make it into the next release (v2.1.0) since I'm in the final stages of testing and will release today but it's on the list for the next release

**Comment by drneavin** [comment]
Needed to rebuild the image for a few other issues when testing so this made it into v2.1.0! Gzipped fastas are now supported. Thanks for the feedback!
