### ISSUE TITLE
Some clarification on your process

### ISSUE THREAD

**Issue by jamesnemesh** [drneavin/Demultiplexing_Doublet_Detecting_Docs#27]
Hi, just some minor clarification on your docs for Dropulation donor assignment:

When you run AssignCellsToSamples, you emit a VCF file:
`--VCF_OUTPUT $DROPULATION_OUTDIR/assignment.vcf`

You should use that as input in doublet detection:
```
DetectDoublets
 --VCF $DROPULATION_OUTDIR/assignment.vcf
```

The VCF emitted by AssignCellsToSamples contains only the sites with coverage in your BAM, so doublet detection will run much faster and use less memory.

You can do the same sort of trick by specifying an output BAM during AssignCellsToSamples:
```
BAM_OUTPUT $DROPULATION_OUTDIR/assignment.bam
```
then
```
DetectDoublets 
--INPUT_BAM $DROPULATION_OUTDIR/assignment.bam
```

Thanks for documenting and making this code available - someone dropped by our github to report a problem then had with a temp directory not being set on their system and linked to your resource.

**Comment by drneavin** [comment]
Thanks @jamesnemesh! I'll make those updates to the documentation. Leaving this open until I've updated

**Comment by jamesnemesh** [comment]
One other small clarification - I prefer to not set `SAMPLE_FILE` in the first step - in my opinion it's nicer to let the algo try hundreds or thousands of donors, and see that it finds the right subset of samples.  If you restrict your data set to the samples you expect, then the approach will of course assign each cell to one of those samples, though the sample may be assigned at low confidence.  It's easier to pick up unexpected donors at this step by testing a wider range of possibilities, which is something we've learned the hard way.

**Comment by drneavin** [comment]
Thanks @jamesnemesh, I'll include a note about that as well. I think it will depend on user experimental designs but completely agree that it's very helpful for finding sample swaps.

I also just want to flag that I tagged you in another issue (#30)  that a user just brought up about low individual annotation using dropulation. I'm not sure if the way that I tagged you would notify you.

**Comment by drneavin** [comment]
updated the docs in [v3.0.0](https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/releases/tag/v3.0.0)
