### ISSUE TITLE
alevin-fry and/or UMI Tools

### ISSUE THREAD

**Issue by changostraw** [drneavin/Demultiplexing_Doublet_Detecting_Docs#33]
Hi @drneavin,
This isn't really an issue, I was just wondering if you have run Demuxafy using the outs from other UMI calling tools like alevin-fry or UMI tools? If one uses a tool that employs pseudoalignment to the transcriptome and creates a rad file instead of a bam file, is it still possible to demultiplex with tools like Demuxalot that require a bam file? As I am doing single nuclei RNA seq on challenging tissues, I wanted to directly compare the resolution of mapping issues between optimizing the cellranger reference and the way that alevin-fry deals with mapping issues. This may be a naive question, but is there a way to convert the rad file to a bam file (I guess not because it wasn't mapped to the genome?), or just use the rad file instead?
Thanks!

**Comment by drneavin** [comment]
Hi @changostraw, I'm not very familiar with rad files but in looking online it looks like it is effectively a counts table that is missing the read information, can you confirm if you have a rad file that this is accurate? In this case, it would be missing the information about the allele at each SNP location so it wouldn't be suitable. Is there the possible of outputting a bam file alevin-fry processing?

**Comment by changostraw** [comment]
Thanks for your input @drneavin. I have already asked the alevin-fry authors about the bam issue, as their psudeoalignment method maps to the transcriptome and not the genome, it probably cannot do this. However, their other method "selective alignment" is a more traditional mapping approach so perhaps can produce a bam. I also might try to see if I can use the cellranger bam from the same pool with the alevin-fry filtered matrix just to see the differences in mapping - thanks!
