### ISSUE TITLE
Unable to download Demuxafy.sif

### ISSUE THREAD

**Issue by MrLocuace** [drneavin/Demultiplexing_Doublet_Detecting_Docs#34]
Hi @drneavin,

I am unable to download Demuxafy.sif following the instructions provided here:
https://demultiplexing-doublet-detecting-docs.readthedocs.io/en/latest/Installation.html

[me@midway3-login4 fastqs]$ wget -O Demuxafy.sif https://www.dropbox.com/scl/fi/g0cuyjwomdavom6u6kb2v/Demuxafy.sif?rlkey=xfey1agg371jo4lubsljfavkh&
[2] 1078293
[1]   Done                    wget -O Demuxafy.sif https://www.dropbox.com/scl/fi/g0cuyjwomdavom6u6kb2v/Demuxafy.sif?rlkey=xfey1agg371jo4lubsljfavkh
[me@midway3-login4 fastqs]$ 
Redirecting output to ‘wget-log.3’.

Please help
Thank you

**Comment by drneavin** [comment]
Hmm, that's a bit strange, I can still use that command to download so I'm wondering if this is related to another issue raised that the & causes issues on some HPC setups. Would you be able to try this instead and let me known if the quotations help:

```
wget -O Demuxafy.sif "https://www.dropbox.com/scl/fi/g0cuyjwomdavom6u6kb2v/Demuxafy.sif?rlkey=xfey1agg371jo4lubsljfavkh&"
```

**Comment by MrLocuace** [comment]
Now it works perfectly well ! Thank you @drneavin

**Comment by drneavin** [comment]
Great!
