### ISSUE TITLE
Vireo tutorial: `bcftools view`: invalid option -- 'N'

### ISSUE THREAD

**Issue by mschilli87** [drneavin/Demultiplexing_Doublet_Detecting_Docs#42]
The current Vireo docs recommend the usage of the `-N` flag for `bcftools view`:

https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/blob/cef151b78b1e5381cd598a4b25fe30a712d76278/docs/source/Vireo.rst?plain=1#L208

However, that is not a valid option.

I assume that's a copy/paste error and the flag should just be ommitted.
~I'll provide a PR shortly.~

--
*edit:* I have verified that Vireo works with the VCF file generated by omitting the `-N` parameter from `bcftools view` and opened https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/pull/43 to adjust the documentation accordingly.

**Comment by drneavin** [comment]
Thanks @mschilli87, yes I think this would be a copy paste error from the vireo command itself. I'll merge the pull request shortly. Thanks for the fixes!
