### ISSUE TITLE
Scrublet error - possible annoy issue?

### ISSUE THREAD

**Issue by changostraw** [drneavin/Demultiplexing_Doublet_Detecting_Docs#44]
Hi @drneavin,
I am having an issue with running Scrublet. I get an error during doublet score calculation:

Reading in barcodes file
Will not filter barcodes as no barcode filtering file was provided.
Counts matrix shape: 11189 rows, 36601 columns
Preprocessing...
Simulating doublets...
Embedding transcriptomes using PCA...
Calculating doublet scores...
Illegal instruction (core dumped)

I looked through the scrublet github and saw these threads: https://github.com/swolock/scrublet/issues/50, https://github.com/swolock/scrublet/issues/28 etc. Since my server was running annoy 1.17, I tried to load annoy-1.16.3 instead and run again. However, this did not appear to work either, so I was wondering if you encountered this at all and had a work around? 
Thanks!
Sarah

**Comment by drneavin** [comment]
Hi @changostraw ,

Thanks for reaching out about this. I've not come across this error previously and just checked but can't reproduce your error. I can load annoy from Demuxafy.sif without issue. Could you confirm the version of Demuxafy that you're using (run `singularity inspect Demuxafy.sif`). 

It looks like the annoy version is 1.17.1 in python 3.7 but this combination isn't listed in that issue link so I'm not sure if this could cause this issue.

Could you also run a few tests at your end to check for annoy as well? 

1. Start a python session from Demuxafy:

```
singularity exec Demuxafy.sif python
```
2. Import annoy
```
import annoy
```
3. Find the location of the annoy package being loaded
```
annoy.__file__
```

I sometimes get core dumps when I haven't allocated enough memory. Is there any chance that this might be happening? How much memory and ram are you dedicating to this run?

Let me know what you get from these steps and we can hopefully resolve it.

**Comment by changostraw** [comment]
thanks @drneavin 
Here is the demuxafy version:
```
Author: = Drew Neavin
Image_version: = 2.1.0
org.label-schema.build-arch: amd64
org.label-schema.build-date: Friday_3_November_2023_1:10:54_UTC
org.label-schema.schema-version: 1.0
org.label-schema.usage.singularity.deffile.bootstrap: docker
org.label-schema.usage.singularity.deffile.from: drneavin/demuxafy:v2.0.1
org.label-schema.usage.singularity.version: 3.11.3-dirty
```
annoy package being loaded:
`'/opt/conda/envs/py37/lib/python3.7/site-packages/annoy/__init__.py'`
Which confirms what you said - that it is running python 3.7 which has annoy/1.17.1. 

Also, when I load my virtual environment with annoy/1.15 and run the demuxafy python session I get the same as above, which makes sense as it is being loaded in the demuxafy image as part of python 3.7 so it overrides my annoy. 

From what I understand reading a lot of the threads on this in the scrublet github and the annoy github - I think any version of python running annoy/1.17 is a problem for scrublet and some other packages as well. It also appears that some people think annoy 1.17 has some issues with docker as well so I don't know if that is a factor here also for singularity. Also, I don't know if it is important, but we don't use singularity on our clusters - I am using apptainer/1.1.8. 

As for memory, I just tried to run demuxafy scrublet with 200G on one node with the same result. I can't imagine it would need more than that...? 

I also tried just running it manually in python/3.11 with annoy/1.15 and it worked with no issues:
`Simulating doublets...
Embedding transcriptomes using PCA...
Calculating doublet scores...
Automatically set threshold at doublet score = 0.17
Detected doublet rate = 5.9%
Estimated detectable doublet fraction = 45.3%
Overall doublet rate:
	Expected   = 6.0%
	Estimated  = 13.1%
Elapsed time: 20.6 seconds`

I did try running it in python within Demuxafy as well, but it didn't work. However, the errors were related to syntax issues. 
`if not os.path.isdir(outdir):
  os.mkdir(outdir)

plt.rc('font', size=14)
plt.rcParams['pdf.fonttype'] = 42`
`SyntaxError: invalid syntax`

So, the core dumping might be an issue of the python/annoy versions that are being used. But I am not sure why you can't reproduce it. If it is just a problem on my cluster, I guess I can just run it in python and try to integrate it with Demuxafy after. 
Thanks!

**Comment by drneavin** [comment]
Thanks @changostraw , I've put this on my to-do list for the next release. Even though I don't see the same behaviour on my cluster, I'll update the package versions so it works for everyone. I'll leave this open until I get around to the next update

**Comment by drneavin** [comment]
annoy downgraded to v1.15 in Demuxafy [v3.0.0](https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/releases/tag/v3.0.0)
