### ISSUE TITLE
Pre-filtering SNPs to exonic regions?

### ISSUE THREAD

**Issue by jamesnemesh** [drneavin/Demultiplexing_Doublet_Detecting_Docs#49]
In the [data preparation](https://demultiplexing-doublet-detecting-docs.readthedocs.io/en/latest/DataPrep.html) section of the docs you mention filtering SNPs to those that overlap exons.  

Is that purely because you find most approaches have sufficient data in the exons and this saves time/computations?  

In human nuclei data sets, STARSolo says that there are a surprisingly large fraction of intronic UMIs - our donor assignment package also recommends using intronic UMs.

<img width="380" alt="image" src="https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/assets/4561831/01465dab-e1fb-4535-8a2d-aeea7d53bffb">

(I'm going to enjoy using your code to give vireo a spin on one of our pools, so thank you for creating this package!)

**Comment by drneavin** [comment]
Hi @jamesnemesh, yes completely agree that there will be lots of coverage over the introns (even in non-nuclei datasets!) but we've found that gene exons are typically enough SNPs (~250k) to differentiate between donors. We also see that some of the methods have longer compute times and memory requirements with more SNPs so we're trying to balance the two. I'll clarify this in the documents for users. I'll leave this open until I get around to my next major update. Thanks for the clarification!

**Comment by mschilli87** [comment]
see https://github.com/drneavin/Demultiplexing_Doublet_Detecting_Docs/commit/c4c5b588b3732fe3d05d32c2a42efcba237ab0d6
