### ISSUE TITLE
Dropulation AssignCellsToSamples error: VCFUtils: Must supply an index file

### ISSUE THREAD

**Issue by lhoranportelance** [drneavin/Demultiplexing_Doublet_Detecting_Docs#55]
Hi -- thanks for creating this tool! 

I'm getting an error when running the AssignCellsToSamples step of Dropulation. It is saying "VCF is not indexed!  Please index and retry." I have indexed the VCF, but I don't see any options to pass the index into this command.

Not sure what to do here. Thanks in advance for your help!

**Comment by drneavin** [comment]
Hi @lhoranportelance,

Thanks for your question! It should automatically find the index if it's there. Have you tried rerunning it now that the vcf has been indexed?

**Comment by lhoranportelance** [comment]
Hi @drneavin,

Thank you for your quick response! I generated a vcf.csi index and tried running it again, and it didn't work. I read a little more into the example you have for Dropulation in the docs, and it seems like a .idx file is generated at some point--does the index need to be in that format? This may be my problem. If so, I will try that and run it again. Does the index need to be in the same directory as the VCF, or should it be in the outs directory?

**Comment by lhoranportelance** [comment]
I believe I figured this issue out. I followed the instructions that were for Vireo for bgzipping and indexing the VCF, then re-ran it. I called the .vcf.bgz for $VCF, and the index (.vcf.bgz.tbi) was in the same directory as the VCF. 

Thanks!

**Comment by drneavin** [comment]
Great! Very glad to hear you worked this out! I'll make a note to add information about this to the documentation. Thanks very much for reaching out!

-Drew
