### ISSUE TITLE
demuxlet Segmentation fault

### ISSUE THREAD

**Issue by changostraw** [drneavin/Demultiplexing_Doublet_Detecting_Docs#7]
Hello,  I keep getting a segmentation fault when I run demuxlet:

singularity exec --bind /project/rrg-gturecki/Sarah/multiplex_test_demuxify_run2_cecum_poolC/outs/raw_feature_bc_matrix Demuxafy.sif popscle dsc-pileup --sam multiplex_test_demuxify_run2_cecum_poolC/outs/possorted_genome_bam.bam --vcf header_sorted_corrected_combined_multiplex_test_genotypes.vcf  --group-list multiplex_test_demuxify_run2_cecum_poolC/outs/raw_feature_bc_matrix/barcodes.tsv.gz  --out /project/rrg-gturecki/Sarah/Demuxafy/Demuxlet/cecum_poolC/pileup

I increased the memory allocation to 250G and it is still giving this error. I am not sure how to troubleshoot this. Is it possible there is a bug?

**Comment by drneavin** [comment]
Hi @changostraw,

I have also come across this with demuxlet pileup and had contacted the developers to help fix this so that it would error instead of result in segmentation fault but they haven't been able to fix this yet which is partly because they do not experience this behavior on their cluster and therefore cannot replicate it. 

Regardless, I notice that you are trying to run the pileup on the raw barcode file. This means that demuxlet will try to count snps for every single droplet in your capture as opposed to the droplets called as cells by cellranger. I would highly recommend running demuxlet using the barcode file in the filtered_feature_bc_matrix directory. Let me know if that helps or if you are still running in to problems.

**Comment by changostraw** [comment]
Okay thanks! I will try running with filtered barcodes. I also realized that the vcf from my genotyping array was aligned to the h19 instead of h38. Could this also create a problem as my bam file is aligned to h38 2020? I am also working on altering the genotyping data to h38.

**Comment by drneavin** [comment]
I don't think that your bam aligned in 2020 to hg38 will cause a problem as long as you lift your vcf to hg38 as well. I have used [picard leftover](https://gatk.broadinstitute.org/hc/en-us/articles/360037060932-LiftoverVcf-Picard-) and [crossmap](http://crossmap.sourceforge.net/) to do this in the past. Either should work fine

**Comment by drneavin** [comment]
There are a couple reasons that souporcell could be crashing. One option is that it ran out of memory and the next time it started the pipeline, it had thought it finished the last step but in reality did not. This functionality is built directly in to souporcell. How many times have you attempted souporcell on the same directory without removing the previous contents?

Second, can you confirm that both your bam and vcf are using the same chromosome encoding? For example, chromosome 1 can be encoded as chr1 or 1. These have to be the same encoding, otherwise issues will arise. Further, how many snps are in your filtered vcf file?

Also, can you provide the information on how you lifted your hg19 to hg38?

there should be instructions for downloading general snp vcfs on the data preparation page: https://demultiplexing-doublet-detecting-docs.readthedocs.io/en/latest/DataPrep.html

let me know if that is not working for you and at what step it is not working. We don’t provide a vcf file since it is rather large and already publicly available.

-Drew

**Comment by changostraw** [comment]
Thanks so much for your response. 
To answer your questions: 
1. I restarted Souporcell once after it crashed and it crashed running vartrix again. I get two crashes reported in the vartrix.err file 
"^[[0m^[[0m^[[31mWell, this is embarrassing.
vartrix had a problem and crashed. To help us diagnose the problem you can send us a crash report.
"We have generated a report file at "/tmp/report-cb2042fa-804e-491a-bc56-91f750318372.toml". Submit an issue or email with the subject of "vartrix Crash Report" and include the report as an attachment.
Authors: Ian Fiddes [ian.fiddes@10xgenomics.com](mailto:ian.fiddes@10xgenomics.com), Patrick Marks [patrick@10xgenomics.com](mailto:patrick@10xgenomics.com)
We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.
Thank you kindly!
^[[0m"

However, no crash report was saved. I am running on a cluster so it would usually say in the main output if it crashed due to memory. The github issues for souporcell I read that you could restart the pipeline and it would see the absence of the vartrix.done file and run varitrix again. Are you saying that I should start over from the beginning - ie remove all the files? Or just remove all the vartrix files?
3. For both the segmentation fault on demuxlet and the crash on souporcell, the bam was h38 and vcf was h19, which is why I thought that could be the issue. I had already corrected all the chromosome naming conventions (changed 1,2,3 to chr1, chr2, chr3 etc) and the order of the header (changed to lexicographical order) to match the bam file etc before I ran everything so that isn't the issue.  
4. I am using two files that are subsets of a larger file for testing. The one that I ran first has just two samples that correspond to a bam file with these 2 samples multiplexed. According to grep -vc '#' subset.vcf - it has 310253 SNPs (5%MAF, 95% call rate). I didn't realize the genome centre had used h19 to align until after I got the errors and I was checking everything again. 
5. Rather than correct these subset files, my colleague has been converting the complete genotype file to h38:
module load picard/2.26.3
java -Xmx13G -jar $EBROOTPICARD/picard.jar LiftoverVcf \
        I=flipped_PLINK_w_pheno_filtered_no_D_I_renamed_chrs.vcf \
        O=flipped_PLINK_w_pheno_filtered_no_D_I_renamed_chrs_hg38.vcf \
        CHAIN=hg19ToHg38.over.chain \
        REJECT=flipped_PLINK_w_pheno_filtered_no_D_I_renamed_chrs_liftover_rejected.vcf \
        R=/cvmfs/soft.mugqic/CentOS6/genomes/species/Homo_sapiens.GRCh38/genome/Homo_sapiens.GRCh38.fa \
        WARN_ON_MISSING_CONTIG=true

However, he ran into some issues as it appears that the input data we received wasn't all on the correct strand or didn't have the allele as reference that matched the reference sequence. So it looks like our genotyping data is problematic in general. We are currently trying to fix this and then I will try Demuxlet and Souporcell with the corrected and full genotyping data again. 

In the meantime I was hoping to confirm that this was issue at least with Souporcell by using a general SNP reference. 
Thanks for your advice!

**Comment by drneavin** [comment]
Hi @changostraw,

Thanks for following up on some of these points. To answer your questions:

1.  Yes, ideally, souporcell should start from where it left off when it runs out of memory but I have noticed that in some situations it thinks that it has finished a step that was really only partially done the time before so deleting everything and restarting that run could be good just to confirm that's not the issue (although based on your responses it seems that it likely isn't). I forgot to ask, but can you confirm that the chromosome encoding in your fasta file is also using chr encoding?

2. I don't think the different genomes will cause the crashes that you're seeing because I think I have accidentally done exactly this in the past (vcf on hg19 and bam on hg38) before realizing they were aligned to different genomes and rerunning it with the correct genomes. However, I may be remembering incorrectly.

3. The number of SNPs seems within the expected ballpark - slightly higher than I typically have but not out of expectation

4. Have you tried Crossmap for lifting the hg19 to hg38? I have found that to be a little less sensitive to chromosome order and other metrics for lifting vcfs.

5. Did you try downloading the hg38 SNPs from the link that I sent? Let me know if you run in to problems with downloading them.

Cheers,
Drew

**Comment by changostraw** [comment]
Okay I will try removing all the vartrix files and if that doesn't work, I will try removing all the files and starting over. The fasta file does have the chr1 naming convention and the lexicographical order as is in my bam file and now in the SNP vcf file:
chr1    248956422	6	50	51
chr10   133797422	253935564	50	51
chr11   135086622	390408942	50	51
chr11_KI270721v1_random 100316  528197322	50	51
chr12   133275309	528299652	50	51
chr13   114364328	664240475	50	51
chr14   107043718	780892097	50	51
chr14_GL000009v2_random 201709  890076715	50	51
chr14_GL000225v1_random 211173  890282484	50	51
chr14_KI270722v1_random 194050  890497906	50	51
chr14_GL000194v1_random 191469  890695862	50	51
chr14_KI270723v1_random 38115   890891186	50	51
chr14_KI270724v1_random 39555   890930089	50	51
chr14_KI270725v1_random 172810  890970461	50	51
chr14_KI270726v1_random 43739   891146753	50	51
chr15   101991189	891191374	50	51
chr15_KI270727v1_random 448248  995222412	50	51
chr16   90338345        995679632	50	51
chr16_KI270728v1_random 1872759 1087824769	50	51
chr17   83257441        1089734991	50	51

I didn't try Crossmap as my colleague had already started converting the SNP data to h38 and it is now complete without any more problems, but I will keep it in mind and suggest that he look into it for next time.

**Comment by changostraw** [comment]
I tried demuxlet with the new vcf file. This new file has 288254 lines, slightly less than the other one probably because it was filtered more conservatively. This vcf was aligned to h38. I used the filtered bam this time. The bam and vcf are in format agreement. However, I am still getting the segmentation fault:

singularity exec --bind /project/rrg-gturecki/Sarah/multiplex_test_demuxify_run2_cecum_poolC/outs Demuxafy.sif popscle dsc-pileup --sam multiplex_test_demuxify_run2_cecum_poolC/outs/possorted_genome_bam.bam --vcf header_filtered_plus_minus_convert_no_D_I_renamed_chrs_hg38.vcf  --group-list multiplex_test_demuxify_run2_cecum_poolC/outs/filtered_feature_bc_matrix/barcodes.tsv.gz  --out /project/rrg-gturecki/Sarah/Demuxafy/Demuxlet/cecum_poolC/pileup
[cramore dsc-pileup] -- Produce pileup of dsc-RNAseq

 Copyright (c) 2009-2017 by Hyun Min Kang and Adrian Tan
 Licensed under the Apache License v2.0 http://www.apache.org/licenses/

Available Options

The following parameters are available. Ones with "[]" are in effect:
           Options for input SAM/BAM/CRAM : --sam [multiplex_test_demuxify_run2_cecum_poolC/outs/possorted_genome_bam.bam],
                                            --tag-group [CB], --tag-UMI [UB],
                                            --exclude-flag [1796]
                Options for input VCF/BCF : --vcf [header_filtered_plus_minus_convert_no_D_I_renamed_chrs_hg38.vcf],
                                            --sm, --sm-list
                           Output Options : --out [/project/rrg-gturecki/Sarah/Demuxafy/Demuxlet/cecum_poolC/pileup],
                                            --sam-verbose [1000000],
                                            --vcf-verbose [10000], --skip-umi
   SNP-overlapping Read filtering Options : --cap-BQ [40], --min-BQ [13],
                                            --min-MQ [20], --min-TD,
                                            --excl-flag [3844]
           Cell/droplet filtering options : --group-list [multiplex_test_demuxify_run2_cecum_poolC/outs/filtered_feature_bc_matrix/barcodes.tsv.gz],
                                            --min-total, --min-uniq, --min-snp

Run with --help for more detailed help messages of each argument.

NOTICE [2022/06/08 12:18:14] - Finished loading 12890 droplet/cell barcodes to consider
NOTICE [2022/06/08 12:18:14] - Initializing BCF reader..
NOTICE [2022/06/08 12:18:14] - Finished identifying 5 samples to load from VCF/BCF
NOTICE [2022/06/08 12:18:14] - Initializing SAM reader..
NOTICE [2022/06/08 12:18:15] - Identified 25 overlapping chromosomes between VCF and BAM
NOTICE [2022/06/08 12:18:15] - WARNING: Cannot find AF field from INFO field in VCF file, now calculate AF from AC/AN
Segmentation fault

Do you think it has something to do with the warning above? thanks!

**Comment by changostraw** [comment]
Hi again,
So I removed the vartrix files and ran souporcell again with the new corrected vcf file and vartrix worked this time. So progress. 
However, it seems to have failed during clustering now:
running vartrix
running souporcell clustering
/opt/souporcell/souporcell/target/release/souporcell -k 2 -a /project/rrg-gturecki/Sarah/Demuxafy/Soupercell/cecum_poolC/alt.mtx -r /project/rrg-gturecki/Sarah/Demuxafy/Soupercell/cecum_poolC/ref.mtx --restarts 100 -b /project/rrg-gturecki/Sarah/multiplex_test_demuxify_run2_cecum_poolC/outs/filtered_feature_bc_matrix/barcodes.tsv.gz --min_ref 10 --min_alt 10 --threads 2 --known_genotypes /project/rrg-gturecki/Sarah/Demuxafy/Soupercell/cecum_poolC/common_variants_covered.vcf --known_genotypes_sample_names 309_GT12139_SingleCellGenotyping_GT-P01_309 400_GT14352_SingleCellGenotyping_GT-P01_400
running souporcell doublet detection
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 598, in <module>
    doublets(args, ref_mtx, alt_mtx, cluster_file)
  File "/opt/souporcell/souporcell_pipeline.py", line 543, in doublets
    subprocess.check_call([directory+"/troublet/target/release/troublet", "--alts", alt_mtx, "--refs", ref_mtx, "--clusters", cluster_file], stdout = dub, stderr = err)
  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/souporcell/troublet/target/release/troublet', '--alts', '/project/rrg-gturecki/Sarah/Demuxafy/Soupercell/cecum_poolC/alt.mtx', '--refs', '/project/rrg-gturecki/Sarah/Demuxafy/Soupercell/cecum_poolC/ref.mtx', '--clusters', '/project/rrg-gturecki/Sarah/Demuxafy/Soupercell/cecum_poolC/clusters_tmp.tsv']' returned non-zero exit status 101.

There is a clustering.done file in the folder, but it is empty:
alt.mtx          clusters.err      common_variants_covered_tmp.vcf  doublets.err  ref.mtx         retagging.done                            variants.done
barcodes.tsv     clusters_tmp.tsv  common_variants_covered.vcf      fastqs.done   remapping.done  souporcell_minimap_tagged_sorted.bam      vartrix.done
clustering.done  clusters.tsv      depth_merged.bed                 minimap.err   retag.err       souporcell_minimap_tagged_sorted.bam.bai

So for demuxlet (as above) the vcf file alignment wasn't the cause of the segmentation fault, but for souporcell it was causing the vartrix crash.

**Comment by changostraw** [comment]
Here is the first few lines of clusters.err file after soupercell crash:
total loci used 1
binomial        0	0	1	0	-80.59912	inf
binomial        1	0	1	0	-80.59912	inf
binomial        0	0	2	0	-23.148155	57.450966
binomial        1	0	2	0	-23.148155	57.450966
binomial        0	0	3	1	-23.14816	-0.000005722046
binomial        1	0	3	1	-23.14816	-0.000005722046
binomial        0	0	4	2	-23.14816	0
binomial        1	0	4	2	-23.14816	0
binomial        0	0	5	3	-23.14816	0
binomial        0	0	6	4	-23.14816	0
binomial        1	0	5	3	-23.14816	0
binomial        0	0	7	5	-23.14816	0
binomial        1	0	6	4	-23.14816	0
binomial        0	0	8	6	-23.14816	0
binomial        1	0	7	5	-23.14816	0
binomial        0	0	9	7	-23.14816	0
binomial        1	0	8	6	-23.14816	0
binomial        0	0	10	8	-23.14816	0
thread 0 iteration 0 done with -23.14816, best so far -23.14816
binomial        1	0	9	7	-23.14816	0
binomial        1	0	10	8	-23.14816	0
thread 1 iteration 0 done with -23.14816, best so far -23.14816
binomial        0	1	1	0	-80.59912	inf
binomial        0	1	2	0	-23.148155	57.450966
binomial        0	1	3	1	-23.14816	-0.000005722046
binomial        1	1	1	0	-80.59912	inf
binomial        1	1	2	0	-23.148155	57.450966
binomial        0	1	4	2	-23.14816	0

Are all these zeros saying that it didn't find any clusters?

**Comment by changostraw** [comment]
So I had to further fix the vcf file - there were still some issues with formatting. But this eventually did fix the segmentation fault with demuxlet. But for some of my sample pools - the ones with low median UMIs per droplet don't seem to work in demuxlet probably because I think there aren't enough variants in the captured droplets. In Vireo, I get a high number of unassigned for these pools for the same reason. I was trying all this with just raw GT data, so possibly if I impute this will increase the number of variants I have in each droplet. I was also thinking that maybe it would work better (in souporcell and vireo) to first demultiplex with the 10000 genomes GT data and then classify the clusters afterwards as this may also result in higher variants per droplet. Otherwise, I guess I will have to go back to the drawing board with my tissue (it is postmortem human tissue so by its nature somewhat degraded).

**Comment by changostraw** [comment]
I am now getting this error with demuxlet though:
FATAL ERROR - 
Cannot extract R2 (1 float value) from INFO field at chr1:792461. Cannot use --geno-error-coeff

terminate called after throwing an instance of 'pException'
  what():  Exception was thrown

**Comment by drneavin** [comment]
Hi @changostraw, I apologize for my delayed response, I've taken some holidays recently. This error is telling you that it needs the R2 value from the INFO column of the vcf file but it doesn't seem you have it there. This would typically be available from the imputation. You may have a different variable for the imputation confidence depending on your imputation method. If you have this information in another field, for example INFO, then use `--r2-info INFO`.

If you don't have this information in the vcf file, simply don't use `--geno-error-coeff 1.0 --geno-error-offset 0.05` in the command. This should fix this error. Let me know if you're still running in to issues.
