### ISSUE TITLE
Location of Tutorials is Unclear

### ISSUE THREAD

**Issue by DarioS** [drneavin/Demultiplexing_Doublet_Detecting_Docs#9]
I read

> We have used this dataset for each of the tutorials.

I downloaded it but I don't see it appear in the latter sections of the user guide. It would also be good to be more explicit about what to do inbetween steps. For example, the guide doesn't explain to run `tar xzvf` on the downloaded file, but it ought to.

**Comment by drneavin** [comment]
Hi @DarioS,

Thanks for pointing this out. I'll add this to the docs now to help users with the next steps after downloading.

Cheers,
Drew
